


-- 테이블 만들기
DROP SEQUENCE WHATIF_SEQ;
DROP TABLE WHATIF;

CREATE TABLE COUNT(
    NO NUMBER(7) PRIMARY KEY, -- 순차번호
    NAME VARCHAR2(30) UNIQUE NOT NULL, -- 닉네임
    GENDER VARCHAR2(10) NOT NULL, -- 성별
    TYPE VARCHAR2(4000) DEFAULT NULL,-- 테스트 결과
    HIT NUMBER(7) DEFAULT 0
);

CREATE SEQUENCE WHATIF_SEQ
MAXVALUE 9999999 NOCACHE NOCYCLE;

-- 1. 닉네임 중복 조회
SELECT * FROM WHATIF WHERE NAME='aaa';

-- 2. 최종 정보입력하기
INSERT INTO WHATIF(NO, NAME, GENDER, TYPE)
    VALUES(WHATIF_SEQ.NEXTVAL, '홍길둥', '남', '어쩌고 저쩌고');
    
-- 3. 전체 정보 조회
SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM(SELECT *
                FROM WHATIF
                WHERE NAME LIKE '%'||'홍'||'%'
                ORDER BY NO DESC) A)
    WHERE RN BETWEEN 2 AND 5;

-- 4. 검색된 멤버 수
SELECT COUNT(*) TOTCNT FROM WHATIF WHERE NAME LIKE '%'||'홍'||'%';






-- 인원만 세줄 테이블
DROP TABLE COUNT;

CREATE TABLE COUNT(
    COUNT NUMBER(7)
);

